/**
 * Reflections routes - HTTP endpoints for reflection management
 * 
 * GET    /api/reflections            - Get all reflections
 * POST   /api/reflections            - Create new reflection
 * GET    /api/reflections/:id        - Get specific reflection
 * DELETE /api/reflections/:id        - Delete specific reflection
 * POST   /api/reflections/delete-all - Delete all reflections (requires confirmation)
 */

import express from 'express';
import ReflectionService from '../../../domain/services/ReflectionService.js';
import LocalFileRepository from '../../storage/LocalFileRepository.js';
import { validateBody } from '../middleware/validation.js';
import { ReflectionSchema } from '../../../domain/entities/Reflection.js';

const router = express.Router();

// Initialize service with repository
const repository = new LocalFileRepository();
const reflectionService = new ReflectionService(repository);

/**
 * GET /api/reflections
 * Get all reflections (sorted by timestamp desc)
 */
router.get('/', async (req, res, next) => {
  try {
    const reflections = await reflectionService.getAllReflections();
    res.json({
      reflections,
      count: reflections.length,
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/reflections/:id
 * Get specific reflection by ID
 */
router.get('/:id', async (req, res, next) => {
  try {
    const { id } = req.params;
    const reflection = await reflectionService.getReflectionById(id);

    if (!reflection) {
      const error = new Error('Reflection not found');
      error.statusCode = 404;
      throw error;
    }

    res.json(reflection);
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/reflections
 * Create new reflection
 * 
 * Schema: mode + content (for text) or mode + visualAttachment (for visual)
 * id, timestamp, aiInteraction are generated by the service
 */
router.post(
  '/',
  async (req, res, next) => {
    try {
      const reflectionData = req.body;
      const created = await reflectionService.createReflection(reflectionData);

      res.status(201).json(created);
    } catch (error) {
      next(error);
    }
  }
);

/**
 * DELETE /api/reflections/:id
 * Delete a specific reflection
 */
router.delete('/:id', async (req, res, next) => {
  try {
    const { id } = req.params;
    const deleted = await reflectionService.deleteReflection(id);
    
    if (!deleted) {
      const error = new Error('Reflection not found');
      error.statusCode = 404;
      throw error;
    }
    
    res.json({
      message: 'Reflection deleted successfully',
      id,
    });
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/reflections/delete-all
 * Delete all reflections (requires "DELETE_ALL" confirmation string per FR-017)
 * 
 * Request body:
 * {
 *   confirmation: "DELETE_ALL"
 * }
 */
router.post('/delete-all', async (req, res, next) => {
  try {
    const { confirmation } = req.body;
    
    // Require exact confirmation string per FR-017
    if (confirmation !== 'DELETE_ALL') {
      const error = new Error('To delete all reflections, you must send confirmation: "DELETE_ALL"');
      error.statusCode = 400;
      throw error;
    }
    
    const deletedCount = await reflectionService.deleteAllReflections();
    
    res.json({
      message: `All reflections deleted successfully`,
      deletedCount,
    });
  } catch (error) {
    next(error);
  }
});

export default router;
